site_name: Kubespider
repo_url: https://github.com/opennaslab/kubespider
repo_name: opennaslab/kubespider
site_dir: site
docs_dir: docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/logo.png
  features:
    - search.highlight
    - navigation.tabs
    - navigation.top
plugins:
  - awesome-pages
  - i18n:
      default_language: zh
      docs_structure: folder
      languages:
        zh:
          name: 中文
          build: true
        en:
          name: English
          build: true
  - search
markdown_extensions:
  - admonition
  - meta
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
  - tables
