# Copyright 2022 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Kubespider china mainland deploy test

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v3

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build images
      run: |
        set -x
        docker buildx build --platform linux/amd64,linux/arm64 -t registry.cn-hangzhou.aliyuncs.com/jwcesign/kubespider:latest -f Dockerfile --load ./
    
    - name: China mainland deploy test
      run: |
        set -x

        #1. Test deploy Kubespider
        export CHINA_MAINLAND=TRUE
        bash hack/install_kubespider.sh
        sleep 60
        docker ps | grep -e kubespider -e aria2-pro
        if [[ $? != 0 ]]; then
          exit 1
        fi
        log=`docker logs kubespider`
        if [[ $log =~ 'Traceback' ]]
        then
          exit 1
        fi

        #2. Test deploy baidu net disk
        bash hack/install_baidunetdisk.sh
        sleep 10
        docker ps | grep -e baidunetdisk
        if [[ $? != 0 ]]; then
          exit 1
        fi

        #3. Test deploy plex
        export PLEX_CLAIM=fake_claim
        bash hack/install_plex.sh
        sleep 10
        docker ps | grep -e plex
        if [[ $? != 0 ]]; then
          exit 1
        fi

        #4. Test deploy thunder
        bash hack/install_thunder.sh
        sleep 10
        docker ps | grep -e xunlei
        if [[ $? != 0 ]]; then
          exit 1
        fi
        
        #5. Test deploy tiktok-dlp
        bash hack/install_tiktokdlp.sh
        sleep 10
        docker ps | grep -e tiktok-dlp
        if [[ $? != 0 ]]; then
          exit 1
        fi

    - name: Find error
      if: ${{ failure() }}
      run: |
        docker ps -a
        docker logs kubespider
        docker logs baidunetdisk
        docker logs aria2-pro
        docker logs plex
        docker logs xunlei
