# Copyright 2022 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Kubespider release
on:
  release:
    types:
    - published
jobs:
  release-assests:
    name: Release Kubespider
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cesign/kubespider:${{  github.ref_name }}
    
    - name: Update the version in script
      run: sed -i "s/latest/v0.1.0/g" hack/install.sh
    
    - name: Uploading assets...
      if: ${{ !env.ACT }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          hack/install.sh
